/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;
import Persistencia.Produto;
import Persistencia.Nacional;
import Persistencia.Estrangeira;
import Cadastrar.Cadastro;

/**
 *
 * @author aluno
 */
public class FrmProduto extends javax.swing.JFrame {
    Cadastro c = new Cadastro();

    /**
     * Creates new form FrmProduto
     */
    public FrmProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lEstado = new javax.swing.JLabel();
        lPais = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        tCod = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        tQuanty = new javax.swing.JTextField();
        tPrice = new javax.swing.JTextField();
        tState = new javax.swing.JTextField();
        tCountry = new javax.swing.JTextField();
        rbtnNacional = new javax.swing.JRadioButton();
        rbtnEstrangeiro = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código Produto");

        jLabel2.setText("Nome produto");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Preço");

        jLabel5.setText("Classes filhas");

        lEstado.setText("Estado");

        lPais.setText("País");

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        tName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnNacional);
        rbtnNacional.setText("Nacional");
        rbtnNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNacionalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnEstrangeiro);
        rbtnEstrangeiro.setText("Estrangeiro");
        rbtnEstrangeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEstrangeiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tState, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCod, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tName, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(tQuanty)
                            .addComponent(tPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rbtnNacional))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnAdd)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnEstrangeiro)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnBusca)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tQuanty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnNacional)
                    .addComponent(rbtnEstrangeiro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstado)
                    .addComponent(lPais)
                    .addComponent(tState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnBusca))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     Produto p=null;
     if (rbtnNacional.isSelected()){
         Nacional n= new Nacional();
         n.setNome(tName.getText());
         n.setEstado(tState.getText());
         n.setTipo("Nacional");
         n.setCodProduto(Integer.parseInt(tCod.getText()));
         n.setQuant(Integer.parseInt(tQuanty.getText()));
         n.setPreco(Double.parseDouble(tPrice.getText()+n.getImposto()));       
         p=n;
         c.Adiciona(p);
     }else{
         Estrangeira e = new Estrangeira();
          e.setNome(tName.getText());
         e.setOrigem(tCountry.getText());
         e.setTipo("Estrangeira");
         e.setCodProduto(Integer.parseInt(tCod.getText()));
         e.setQuant(Integer.parseInt(tQuanty.getText()));
         e.setPreco(Double.parseDouble(tPrice.getText()+e.getAliquota()));
         p=e;
         c.Adiciona(p);
         
     }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
       Produto p=null;
       p=c.Recupera(tName.getText());
        if (p.getTipo().equals("Nacional")){
            Nacional n= (Nacional) p;
            tCod.setText(String.valueOf(n.getCodProduto())); 
            tQuanty.setText(String.valueOf(n.getQuant()));
            tPrice.setText(String.valueOf(n.getPreco()));
            tName.setText(String.valueOf(n.getNome()));
            tState.setText(String.valueOf(n.getEstado()));
            rbtnNacional.setFocusable(true);
            rbtnNacional.isSelected();
        }
        else{
            Estrangeira e = (Estrangeira) p;
            tCod.setText(String.valueOf(e.getCodProduto())); 
            tQuanty.setText(String.valueOf(e.getQuant()));
            tPrice.setText(String.valueOf(e.getPreco()));
            tName.setText(String.valueOf(e.getNome()));
            tCountry.setText(String.valueOf(e.getOrigem()));
            rbtnEstrangeiro.setFocusable(true);
            rbtnEstrangeiro.isSelected();
        }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void rbtnNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNacionalActionPerformed
       if (rbtnNacional.isSelected()){
        tCountry.setVisible(false);
        lPais.setVisible(false);
        tState.setVisible(true);
        lEstado.setVisible(true);
       }
    }//GEN-LAST:event_rbtnNacionalActionPerformed

    private void rbtnEstrangeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEstrangeiroActionPerformed
        if (rbtnEstrangeiro.isSelected()){
        tState.setVisible(false);
        lEstado.setVisible(false);
        tCountry.setVisible(true);
        lPais.setVisible(true);
        
        }
    }//GEN-LAST:event_rbtnEstrangeiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBusca;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lPais;
    private javax.swing.JRadioButton rbtnEstrangeiro;
    private javax.swing.JRadioButton rbtnNacional;
    private javax.swing.JTextField tCod;
    private javax.swing.JTextField tCountry;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tPrice;
    private javax.swing.JTextField tQuanty;
    private javax.swing.JTextField tState;
    // End of variables declaration//GEN-END:variables
}
