package Visao;
import javax.swing.JOptionPane;
import Cadastro.Cadastrar;
import Persistencia.Produto;
/**
 *
 * @author Flavio Losso
 */
public class FrmProd extends javax.swing.JFrame {
 Cadastrar c = new Cadastrar();
 private int numreg;
    /**
     * Creates new form FrmProd
     */
    public FrmProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxTam = new javax.swing.JComboBox();
        tCod = new javax.swing.JTextField();
        tNome = new javax.swing.JTextField();
        tQnt = new javax.swing.JTextField();
        tPco = new javax.swing.JTextField();
        btnAdc = new javax.swing.JButton();
        btnPsqn = new javax.swing.JButton();
        btnPsqc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mbRemover = new javax.swing.JMenuItem();
        mbSaida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mbMaiorn = new javax.swing.JMenuItem();
        mbMedp = new javax.swing.JMenuItem();
        mbPabaixomed = new javax.swing.JMenuItem();
        mbApa = new javax.swing.JMenuItem();
        mbTot = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                ativado(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Código");

        jLabel3.setText("Tamanho");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Preço");

        cbxTam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pequeno", "Medio", "Grande", "Extra-Grande" }));

        tCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodActionPerformed(evt);
            }
        });

        btnAdc.setText("Adicionar");
        btnAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcActionPerformed(evt);
            }
        });

        btnPsqn.setText("Busca Nome");
        btnPsqn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsqnActionPerformed(evt);
            }
        });

        btnPsqc.setText("Busca Código");
        btnPsqc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsqcActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        mbRemover.setText("Remover Produto");
        mbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbRemoverActionPerformed(evt);
            }
        });
        jMenu1.add(mbRemover);

        mbSaida.setText("Saida");
        mbSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSaidaActionPerformed(evt);
            }
        });
        jMenu1.add(mbSaida);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funções");

        mbMaiorn.setText("Prod. de Maior nome");
        mbMaiorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbMaiornActionPerformed(evt);
            }
        });
        jMenu2.add(mbMaiorn);

        mbMedp.setText("Média de preço");
        mbMedp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbMedpActionPerformed(evt);
            }
        });
        jMenu2.add(mbMedp);

        mbPabaixomed.setText("Prod. Abaixo da média");
        mbPabaixomed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbPabaixomedActionPerformed(evt);
            }
        });
        jMenu2.add(mbPabaixomed);

        mbApa.setText("Prefixo APA");
        mbApa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbApaActionPerformed(evt);
            }
        });
        jMenu2.add(mbApa);

        mbTot.setText("Valor do Estoque");
        mbTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbTotActionPerformed(evt);
            }
        });
        jMenu2.add(mbTot);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tPco)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tCod, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPsqn)
                            .addComponent(btnPsqc))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tNome)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cbxTam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tQnt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tPco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPsqn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPsqc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCodActionPerformed
       
    private void btnAdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcActionPerformed
        Produto p = new Produto();
 if(tNome.getText().equals("")||String.valueOf(tPco).equals("")||String.valueOf(tQnt).equals("")){
        JOptionPane.showMessageDialog(null,"Preencha todos os campos");
        System.exit(10);
        }
 else
        numreg++;
         tCod.setText(String.valueOf(numreg));
        p.setcodprod(numreg);
        p.setNome(tNome.getText());
        p.setTam(String.valueOf(cbxTam.getSelectedItem()));
        p.setPreco(Double.parseDouble(tPco.getText()));
        p.setQuant(Integer.parseInt(tQnt.getText()));
        c.adciona(p);
        System.out.println(tNome.getText().substring(0, 3));
    }//GEN-LAST:event_btnAdcActionPerformed

    private void btnPsqnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsqnActionPerformed
 int i=c.PesqNome(JOptionPane.showInputDialog(null,"Digite o nome do produto"));
      
       tCod.setEnabled(true);
       tCod.setText(String.valueOf(c.getlistProd().get(i).getcodprod()));
       tNome.setText(c.getlistProd().get(i).getNome());
       tPco.setText(String.valueOf(c.getlistProd().get(i).getPreco()));
       tQnt.setText(String.valueOf(c.getlistProd().get(i).getQuant()));
       cbxTam.setSelectedItem(c.getlistProd().get(i).getTam());
       tCod.setEnabled(false);
    }//GEN-LAST:event_btnPsqnActionPerformed

    private void btnPsqcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsqcActionPerformed
 int i=c.consporCod(Integer.parseInt(JOptionPane.showInputDialog(null,"Digite o código do produto")));
 
       tCod.setEnabled(true);
       tCod.setText(String.valueOf(c.getlistProd().get(i).getcodprod()));
       tNome.setText(c.getlistProd().get(i).getNome());
       tPco.setText(String.valueOf(c.getlistProd().get(i).getPreco()));
       tQnt.setText(String.valueOf(c.getlistProd().get(i).getQuant()));
       cbxTam.setSelectedItem(c.getlistProd().get(i).getTam());
       tCod.setEnabled(false);
    }//GEN-LAST:event_btnPsqcActionPerformed

    private void mbMaiornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbMaiornActionPerformed
        String na=c.maiorNome();
        JOptionPane.showMessageDialog(null,"O produto de maior nome é "+na);
    }//GEN-LAST:event_mbMaiornActionPerformed

    private void mbMedpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbMedpActionPerformed
        double med=c.med();
        JOptionPane.showMessageDialog(null,"A média de preço dos produtos é "+med);
    }//GEN-LAST:event_mbMedpActionPerformed

    private void mbPabaixomedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbPabaixomedActionPerformed
        double am=c.prodabmed();
        JOptionPane.showMessageDialog(null,"O número de produtos abaixo da média de preço é "+am);
    }//GEN-LAST:event_mbPabaixomedActionPerformed

    private void mbApaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbApaActionPerformed
       c.qntpre();
    }//GEN-LAST:event_mbApaActionPerformed

    private void mbTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbTotActionPerformed
        double v=c.valorest();
        JOptionPane.showMessageDialog(null,"O valor total do estoque é "+v);
    }//GEN-LAST:event_mbTotActionPerformed

    private void mbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbRemoverActionPerformed
     int i=c.remov(Integer.parseInt(JOptionPane.showInputDialog(null,"Informe o código do produto")));
     if(i==0){
         JOptionPane.showMessageDialog(null,"Item removido");
     }
     
     else{
         JOptionPane.showMessageDialog(null,"Erro ao remover do registro");
     }
    }//GEN-LAST:event_mbRemoverActionPerformed

    private void mbSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSaidaActionPerformed
      int resp=JOptionPane.showConfirmDialog(null, "Deseja sair?");
      if (resp==0){
          JOptionPane.showMessageDialog(null,"Tchau Tchau");
          System.exit(0);
      }
      else{
          System.out.println(resp);
      }
    }//GEN-LAST:event_mbSaidaActionPerformed

    private void ativado(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ativado
     tCod.setEnabled(false);
        tNome.requestFocus();
    }//GEN-LAST:event_ativado

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdc;
    private javax.swing.JButton btnPsqc;
    private javax.swing.JButton btnPsqn;
    private javax.swing.JComboBox cbxTam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mbApa;
    private javax.swing.JMenuItem mbMaiorn;
    private javax.swing.JMenuItem mbMedp;
    private javax.swing.JMenuItem mbPabaixomed;
    private javax.swing.JMenuItem mbRemover;
    private javax.swing.JMenuItem mbSaida;
    private javax.swing.JMenuItem mbTot;
    private javax.swing.JTextField tCod;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tPco;
    private javax.swing.JTextField tQnt;
    // End of variables declaration//GEN-END:variables
}
